<?php

namespace AppBundle\Entity\Repository;

/**
 * GaleriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaRepository extends \Doctrine\ORM\EntityRepository
{
}
