<?php

namespace AppBundle\Entity\Repository;

/**
 * PromocionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromocionRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function find4Site($count) {
		
		$qb = $this->createQueryBuilder('p')
			->select('p, CASE WHEN p.generica = 0 THEN 1 ELSE 0 END as ord')
			->andWhere('( p.fechaPublicacion <= CURRENT_TIMESTAMP() AND p.fechaVencimiento >= CURRENT_TIMESTAMP() ) OR p.generica = 1')
			->orderBy('ord','DESC')
			->addOrderBy('p.orden','ASC')
			->setMaxResults($count)
		;
		
		$promociones = array();
		$res = $qb->getQuery()->execute();
		foreach($res as $data) {
			$promociones[] = $data[0];
		}
		return $promociones;
		
	}
	
}
